### ISSUE TITLE
minimum GSL version requirement

### ISSUE THREAD

**Issue by bastistician** [RobinHankin/gsl#17]
Both

https://github.com/RobinHankin/gsl/blob/d28d8fe3cc0fd9e7f5f796ca6bb34f05aab49fbf/DESCRIPTION#L8

and

https://github.com/RobinHankin/gsl/blob/d28d8fe3cc0fd9e7f5f796ca6bb34f05aab49fbf/configure.ac#L50

seem to be outdated.

[Ubuntu 18.04 ships GSL 2.4](https://packages.ubuntu.com/bionic/libgsl-dev) but configuration of the newly released gsl 2.1-7 fails with

```
configure: error: Need GSL version >= 1.16
ERROR: configuration failed for package 'gsl'
```

**Comment by wviechtb** [comment]
Commit 3e826bb92c03d5461a2ce8414b18c434d36fcc37 updated the requirement to 2.5 (which ships with 20.04) but that error message wasn't updated (in [configure](https://github.com/RobinHankin/gsl/blob/d28d8fe3cc0fd9e7f5f796ca6bb34f05aab49fbf/configure#L2659) and [configure.ac](https://github.com/RobinHankin/gsl/blob/d28d8fe3cc0fd9e7f5f796ca6bb34f05aab49fbf/configure.ac#L50)).

**Comment by RobinHankin** [comment]
thanks for this, will fix shortly

**Comment by bastistician** [comment]
Thanks. The system requirement stated in the DESCRIPTION would also need an update.

**Comment by aitap** [comment]
Currently, the `./configure` test checks for any minor version of 5 and above, not >= 2.5:

```
$ cat version.c
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char ** argv) {
	int major, minor;
	if (argc != 2) return -1;
	if (sscanf(argv[1], "%d.%d", &major, &minor) != 2) return -1;
	exit(minor < 5);
	exit(major < 2);
}
$ cc -o version version.c
$ ./version 1.5 && echo test passed
test passed
$ ./version 3.0 || echo test failed
test failed
```

This happens because the first call to `exit` terminates the process, ignoring the value of `major`.
Comparing versions is hard [[1](https://devblogs.microsoft.com/oldnewthing/20040213-00/?p=40633), [2](https://devblogs.microsoft.com/oldnewthing/20050413-56/?p=35913)]. I think that a correct way to compare versions would be something along the lines of:

```
if (major < 2) return 1;
if (major > 2) return 0;
if (minor < 5) return 1;
return 0;
```
